version: '3.9'
services:
  database:
    image: postgres
    platform: linux/x86_64
    container_name: wallet-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 10s
      retries: 5
    networks:
      - wallet_back-db

  backend:
    platform: linux/x86_64
    container_name: wallet_backend
    build: ./backend
    working_dir: /api
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
    networks:
      - wallet_front-back
      - wallet_back-db

  frontend:
    platform: linux/x86_64
    container_name: wallet_frontend
    build: ./frontend
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
    networks:
      - wallet_front-back

networks:
  wallet_front-back: {}
  wallet_back-db: {}