version: '3.9'
services:
  database:
    image: postgres
    platform: linux/x86_64
    container_name: wallet_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
    networks:
      - wallet_back-db

  backend:
    platform: linux/x86_64
    container_name: wallet_backend
    build: ./backend
    command: npm run dev
    working_dir: /api
    ports:
      - 3001:3001
    restart: always
    volumes: 
      - ./backend/src:/api/src
    depends_on:
      - database
    networks:
      - wallet_front-back
      - wallet_back-db

  frontend:
    platform: linux/x86_64
    container_name: wallet_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app
    restart: always
    volumes: 
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - wallet_front-back

networks:
  wallet_front-back: {}
  wallet_back-db: {}
